### ISSUE TITLE
Zmiany w aplikacjach klienckich

### ISSUE THREAD

**Issue by jakubgalka** [DL-Projekt/Interfejs-glosowy#4]
Informacja od Marcina w sprawie aplikacji Techmo (Sarmata, TTS, etc.):  https://github.com/marcinwitkowski/tm-clients

Zrobiłem update klientów na githubie. Dodałem TTS i Sarmatę na SRGS. Dodatkowo w najnowszej wersji klientów usunąłem zahardcodowane adresy IP - teraz każdy przykładowy klient pobiera je bezpośrednio z jsona, którego wystawiam na mojej stronie na home.agh.edu.pl. Lepiej z tego korzystać bo w razie pożarów/dropów serwerów, będę przerzucał serwisy i tam zmieniał odpowiednio adresy

**Comment by ArdeoDeo** [comment]
Zmiana planów, obecnie korzystamy z Android Google Speech
